# Generated by Django 4.2.3 on 2023-08-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookmarkCollectionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("created", models.DateTimeField(auto_now=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BookmarkModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("url", models.URLField(unique=True)),
                (
                    "url_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Website"),
                            (2, "Book"),
                            (3, "Article"),
                            (4, "Music"),
                            (5, "Video"),
                        ],
                        default=1,
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("created", models.DateTimeField(auto_now=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "collections",
                    models.ManyToManyField(
                        related_name="bookmarks", to="api.bookmarkcollectionmodel"
                    ),
                ),
            ],
        ),
    ]
