# Generated by Django 4.2.3 on 2023-08-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmarkmodel",
            name="image",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="bookmarkmodel",
            name="url_type",
            field=models.CharField(
                choices=[
                    ("website", "Website"),
                    ("book", "Book"),
                    ("article", "Article"),
                    ("music", "Music"),
                    ("video", "Video"),
                ],
                default="website",
                max_length=10,
            ),
        ),
    ]
